### ISSUE TITLE
elm-package install doesn't work

### ISSUE THREAD

**Issue by yogsototh** [koyachi/elm-sha#1]
Hi,

I tried to make a simple elm-package install and while the install works, when I try to use the library with
elm-make it complains:

Error when searching for modules imported by module 'Sha':
    Could not find module 'Native.Sha'

Potential problems could be:
- Misspelled the module name
- Need to add a source directory or new dependency to elm-package.json

I didn't tried to investigate further.

Best.

**Comment by yogsototh** [comment]
Apparently it lacks 

```
"native":true
```

 entry in the elm-package.json

After doing this I do not encounter the compilation problem. Still I am unable to use the package with a runtime error.

```
digest (createHash "toto")


Error: : is not supported (we accept pull requests)
```

**Comment by koyachi** [comment]
I wasn't know about '"native":true' and Elm's Native package review process when I uploaded elm-sha Ver.1.0.0. So elm-sha Ver.1.0.0 doesn't work.

elm-sha 1.0.1 is in review queue: https://github.com/elm-lang/package.elm-lang.org/issues/33.

**Comment by yogsototh** [comment]
thanks!
