### ISSUE TITLE
Minimal example doesn't seems to work

### ISSUE THREAD

**Issue by yogsototh** [koyachi/elm-sha#2]
I've done this minimal example (1.0.1) and I get the following error at runtime:

```
import Graphics.Element exposing (..)
import Sha

main : Element
main = show (Sha.digest "hex" (Sha.createHash "hello"))
```

```
hello is not supported (we accept pull requests)
```

**Comment by koyachi** [comment]
Sha.createHash accepts one of these hash algorithms: ["sha1", "sha", "sha256", "sha512"]. These are same as sha.js's supported hashes.
https://github.com/crypto-browserify/sha.js#supported-hashes

examples:
- https://github.com/koyachi/elm-sha/blob/master/examples/Main.elm
- https://github.com/koyachi/elm-sha/blob/master/tests/Test.elm

**Comment by yogsototh** [comment]
Ooops, really sorry I didn't quite understood the API correctly. It works like a charm.

You might be able to enforce good usage by creating data structure instead of String:

type HashType = SHA1 | SHA | SHA256 | SHA512
with

createHash : HashType -> Hash

And certainly the same for digest:

type Digest = HEX | B64 | BIN

Best,
Y.

**Comment by koyachi** [comment]
> You might be able to enforce good usage by creating data structure instead of String:
> 
> type HashType = SHA1 | SHA | SHA256 | SHA512
> with
> 
> createHash : HashType -> Hash
> 
> And certainly the same for digest:
> 
> type Digest = HEX | B64 | BIN

Ah, yes. Specifying Hash Algorithm and Digest Encoding with string is not Elm-way.
I'll fix this with elm-sha Ver.1.0.2.
Thanks!
